import { PropTypes } from 'prop-types';

const BeachObject = {
  id: PropTypes.string.isRequired,
  comunidad_autonoma: PropTypes.string.isRequired,
  provincia: PropTypes.string.isRequired,
  isla: PropTypes.string.isRequired ,
  codigo_ine_municipio: PropTypes.string.isRequired,
  termino_municipal: PropTypes.string.isRequired,
  web_municipal: PropTypes.string.isRequired,
  identificador: PropTypes.string.isRequired,
  nombre: PropTypes.string.isRequired,
  nombre_alternativo: PropTypes.string.isRequired ,
  nombre_alternativo_2: PropTypes.string.isRequired,
  descripcion: PropTypes.string.isRequired,
  longitud: PropTypes.string.isRequired,
  anchura: PropTypes.string.isRequired,
  variacion_anchura: PropTypes.string.isRequired,
  grado_ocupacion: PropTypes.string.isRequired,
  grado_urbanizacion: PropTypes.string.isRequired,
  paseo_maritimo: PropTypes.string.isRequired,
  tipo_paseo_maritimo: PropTypes.string.isRequired,
  tipo_de_arena: PropTypes.string.isRequired,
  condiciones_baño: PropTypes.string.isRequired,
  zona_fondeo_balizada: PropTypes.string.isRequired,
  nudismo: PropTypes.string.isRequired,
  vegetacion: PropTypes.string.isRequired,
  vegetacion_lugar: PropTypes.string.isRequired,
  actuaciones: PropTypes.string.isRequired,
  actuaciones_tipo: PropTypes.string.isRequired,
  bandera_azul: PropTypes.string.isRequired,
  auxilio_y_salvamento: PropTypes.string.isRequired,
  auxilio_y_salvamento_desc:PropTypes.string.isRequired ,
  señalizacion_peligro: PropTypes.string.isRequired,
  señalizacion_peligro_desc: PropTypes.string.isRequired,
  forma_de_acceso: PropTypes.string.isRequired,
  señalizacion_accesos: PropTypes.string.isRequired,
  acceso_discapacitados: PropTypes.string.isRequired,
  carretera_mas_proxima: PropTypes.string.isRequired,
  autobus: PropTypes.string.isRequired,
  autobus_tipo: PropTypes.string.isRequired,
  aparcamiento: PropTypes.string.isRequired,
  aparcamiento_seguridad: PropTypes.string.isRequired ,
  aparcamiento_num_plazas: PropTypes.string.isRequired,
  aseos: PropTypes.string.isRequired,
  lavapies: PropTypes.string.isRequired,
  duchas: PropTypes.string.isRequired,
  telefonos: PropTypes.string.isRequired,
  papelera: PropTypes.string.isRequired,
  servicio_limpieza: PropTypes.string.isRequired,
  alquiler_sombrillas: PropTypes.string.isRequired,
  alquiler_hamacas: PropTypes.string.isRequired,
  alquiler_nauticos: PropTypes.string.isRequired,
  oficina_turismo: PropTypes.string.isRequired,
  establecimiento_comida: PropTypes.string.isRequired,
  establecimiento_bebida: PropTypes.string.isRequired,
  zona_infantil: PropTypes.string.isRequired,
  zona_deportiva: PropTypes.string.isRequired,
  club_nautico: PropTypes.string.isRequired,
  submarinismo: PropTypes.string.isRequired,
  zona_surf: PropTypes.string.isRequired,
  observaciones: PropTypes.string.isRequired,
  coordenada_x: PropTypes.string.isRequired,
  coordenada_y: PropTypes.string.isRequired,
  huso: PropTypes.string.isRequired,
  coordenada_geografica_longitud: PropTypes.string.isRequired,
  coordenada_geografica_latitud: PropTypes.string.isRequired,
  puerto_deportivo: PropTypes.string.isRequired,
  web_puerto_deportivo: PropTypes.string.isRequired,
  distancia_puerto_deportivo: PropTypes.string.isRequired,
  hospital: PropTypes.string.isRequired,
  direccion_hospital: PropTypes.string.isRequired,
  telefono_hospital: PropTypes.string.isRequired,
  distancia_hospital: PropTypes.string.isRequired,
  composicion: PropTypes.string.isRequired,
  fachada_litoral: PropTypes.string.isRequired,
  espacio_protegido: PropTypes.string.isRequired,
  espacio_protegido_desc: PropTypes.string.isRequired ,
  links: PropTypes.string.isRequired,
  images: PropTypes.string.isRequired

}

export default BeachObject;