export const SET_COUNTRY_BEACHES_START = 'SET_COUNTRY_BEACHES_START';
export const SET_COUNTRY_BEACHES_SUCCEED = 'SET_COUNTRY_BEACHES_SUCCEED';
export const SET_COUNTRY_BEACHES_FAILED = 'SET_COUNTRY_BEACHES_FAILED';

export const SET_REGION_BEACHES = 'SET_REGION_BEACHES';

export const SET_MAP_RESULTS_SELECT = 'SET_MAP_RESULTS_SELECT';
export const SET_MAP_RESULTS_INPUT = 'SET_MAP_RESULTS_INPUT';
export const SET_RETURN_FROM_DETAILS = 'SET_RETURN_FROM_DETAILS';

export const SET_MAP_AREA = 'SET_MAP_ARE';