export const SET_COUNTRY_BEACHES_START = 'SET_COUNTRY_BEACHES_START';
export const SET_COUNTRY_BEACHES_SUCCEED = 'SET_COUNTRY_BEACHES_SUCCEED';
export const SET_COUNTRY_BEACHES_FAILED = 'SET_COUNTRY_BEACHES_FAILED';

export const SET_REGION_BEACHES = 'SET_REGION_BEACHES';