// flow-typed signature: 2354e6ca56a7c7c3b056f396cb54054e
// flow-typed version: <<STUB>>/@amcharts/amcharts3-react_v^3.1.0/flow_v0.106.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@amcharts/amcharts3-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@amcharts/amcharts3-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@amcharts/amcharts3-react/amcharts3-react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@amcharts/amcharts3-react/amcharts3-react.js' {
  declare module.exports: $Exports<'@amcharts/amcharts3-react/amcharts3-react'>;
}
declare module '@amcharts/amcharts3-react/index' {
  declare module.exports: $Exports<'@amcharts/amcharts3-react'>;
}
declare module '@amcharts/amcharts3-react/index.js' {
  declare module.exports: $Exports<'@amcharts/amcharts3-react'>;
}
