// flow-typed signature: 4ca503506d40230b4f093a919c2b118f
// flow-typed version: <<STUB>>/react-textfit_v^1.1.0/flow_v0.106.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textfit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-textfit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-textfit/lib' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/Textfit' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/utils/innerSize' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/utils/series' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/utils/throttle' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/utils/uniqueId' {
  declare module.exports: any;
}

declare module 'react-textfit/lib/utils/whilst' {
  declare module.exports: any;
}

declare module 'react-textfit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-textfit/lib/index' {
  declare module.exports: $Exports<'react-textfit/lib'>;
}
declare module 'react-textfit/lib/index.js' {
  declare module.exports: $Exports<'react-textfit/lib'>;
}
declare module 'react-textfit/lib/Textfit.js' {
  declare module.exports: $Exports<'react-textfit/lib/Textfit'>;
}
declare module 'react-textfit/lib/utils/innerSize.js' {
  declare module.exports: $Exports<'react-textfit/lib/utils/innerSize'>;
}
declare module 'react-textfit/lib/utils/series.js' {
  declare module.exports: $Exports<'react-textfit/lib/utils/series'>;
}
declare module 'react-textfit/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-textfit/lib/utils/shallowEqual'>;
}
declare module 'react-textfit/lib/utils/throttle.js' {
  declare module.exports: $Exports<'react-textfit/lib/utils/throttle'>;
}
declare module 'react-textfit/lib/utils/uniqueId.js' {
  declare module.exports: $Exports<'react-textfit/lib/utils/uniqueId'>;
}
declare module 'react-textfit/lib/utils/whilst.js' {
  declare module.exports: $Exports<'react-textfit/lib/utils/whilst'>;
}
declare module 'react-textfit/webpack.config.js' {
  declare module.exports: $Exports<'react-textfit/webpack.config'>;
}
