// flow-typed signature: c0173cf30c16b2193f0177d772966b48
// flow-typed version: <<STUB>>/react-background-video-player_v^1.1.6/flow_v0.106.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-background-video-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-background-video-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-background-video-player/dist' {
  declare module.exports: any;
}

declare module 'react-background-video-player/test/test' {
  declare module.exports: any;
}

declare module 'react-background-video-player/test/testSources' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-background-video-player/dist/index' {
  declare module.exports: $Exports<'react-background-video-player/dist'>;
}
declare module 'react-background-video-player/dist/index.js' {
  declare module.exports: $Exports<'react-background-video-player/dist'>;
}
declare module 'react-background-video-player/index' {
  declare module.exports: $Exports<'react-background-video-player'>;
}
declare module 'react-background-video-player/index.js' {
  declare module.exports: $Exports<'react-background-video-player'>;
}
declare module 'react-background-video-player/test/test.js' {
  declare module.exports: $Exports<'react-background-video-player/test/test'>;
}
declare module 'react-background-video-player/test/testSources.js' {
  declare module.exports: $Exports<'react-background-video-player/test/testSources'>;
}
