// flow-typed signature: 1d4ada9d266c4db97ccdfe6ef7282741
// flow-typed version: <<STUB>>/react-image-fallback_v^8.0.0/flow_v0.106.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-fallback/lib' {
  declare module.exports: any;
}

declare module 'react-image-fallback/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-fallback/lib/index' {
  declare module.exports: $Exports<'react-image-fallback/lib'>;
}
declare module 'react-image-fallback/lib/index.js' {
  declare module.exports: $Exports<'react-image-fallback/lib'>;
}
declare module 'react-image-fallback/src/index' {
  declare module.exports: $Exports<'react-image-fallback/src'>;
}
declare module 'react-image-fallback/src/index.js' {
  declare module.exports: $Exports<'react-image-fallback/src'>;
}
