// flow-typed signature: c3d814dad940546b9aa770a77696d4a6
// flow-typed version: <<STUB>>/react-open-weather_v^0.4.0/flow_v0.106.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-open-weather'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-open-weather' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-open-weather/lib/js/ReactWeather' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/components/DaysForecast' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/components/ReactWeather' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/components/TodayForecast' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/components/WeatherIcon' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/icons' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/lang' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/main' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/utils' {
  declare module.exports: any;
}

declare module 'react-open-weather/src/js/XuApi' {
  declare module.exports: any;
}

declare module 'react-open-weather/webpack.config.build' {
  declare module.exports: any;
}

declare module 'react-open-weather/webpack.config.dev' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-open-weather/lib/js/ReactWeather.js' {
  declare module.exports: $Exports<'react-open-weather/lib/js/ReactWeather'>;
}
declare module 'react-open-weather/src/js/components/DaysForecast.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/components/DaysForecast'>;
}
declare module 'react-open-weather/src/js/components/ReactWeather.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/components/ReactWeather'>;
}
declare module 'react-open-weather/src/js/components/TodayForecast.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/components/TodayForecast'>;
}
declare module 'react-open-weather/src/js/components/WeatherIcon.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/components/WeatherIcon'>;
}
declare module 'react-open-weather/src/js/icons.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/icons'>;
}
declare module 'react-open-weather/src/js/lang.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/lang'>;
}
declare module 'react-open-weather/src/js/main.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/main'>;
}
declare module 'react-open-weather/src/js/utils.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/utils'>;
}
declare module 'react-open-weather/src/js/XuApi.js' {
  declare module.exports: $Exports<'react-open-weather/src/js/XuApi'>;
}
declare module 'react-open-weather/webpack.config.build.js' {
  declare module.exports: $Exports<'react-open-weather/webpack.config.build'>;
}
declare module 'react-open-weather/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-open-weather/webpack.config.dev'>;
}
